/**
 * `npm run test:e2e [-- <playwright args>]`: the e2e suite on its own
 * Supabase stack, so the dev database is never touched.
 *
 *   1. Writes .e2e-stack/ (gitignored): a copy of supabase/config.toml with
 *      project_id "<id>-e2e", every port moved from 543xx to 553xx, the auth
 *      site URL on the test server's port, and Studio, analytics and the edge
 *      runtime off; plus a fresh copy of supabase/migrations.
 *   2. Starts that stack if it is not running (`supabase start --workdir`),
 *      resets it (every migration from scratch) and seeds it with
 *      SEED_ACCOUNTS=e2e (e2e-admin@, e2e-barista@, e2e-customer@).
 *   3. Writes its URL and keys to .e2e-stack/.env.e2e, which
 *      playwright.config.ts reads.
 *   4. Fingerprints the dev database (counts and hashes of everything a run
 *      could change; scripts/lib/local-stack.mjs), runs Playwright, and
 *      fingerprints it again. Any difference fails the run, as does test data
 *      (e2e-* accounts) found there.
 *
 * The stack is left running for the next run; `npm run db:e2e:stop` stops it.
 * It needs about 1 GB of Docker memory on top of the dev stack.
 */
import { spawnSync } from "node:child_process";
import { randomBytes } from "node:crypto";
import { cpSync, mkdirSync, readFileSync, rmSync, writeFileSync } from "node:fs";
import { connect } from "node:net";
import { join } from "node:path";

import {
  containerRunning,
  databaseContainer,
  fingerprint,
  fingerprintChanges,
  parseEnv,
  projectIdOf,
  psqlJson,
} from "./lib/local-stack.mjs";

const STACK_DIR = ".e2e-stack";
const ENV_FILE = join(STACK_DIR, ".env.e2e");
const PORT_OFFSET = 1000;
const TEST_SERVER_PORT = 3100;
/** Not needed by the suite; leaving them out roughly halves the stack's memory. */
const EXCLUDED_SERVICES = ["studio", "postgres-meta", "edge-runtime", "logflare", "vector", "imgproxy", "supavisor"];
const OFF_SECTIONS = new Set(["studio", "analytics", "edge_runtime"]);

const devProjectId = projectIdOf();
const projectId = `${devProjectId}-e2e`;
const stackContainer = databaseContainer(projectId);
const devContainer = databaseContainer(devProjectId);
const isWindows = process.platform === "win32";

function step(message) {
  console.log(`\n[e2e] ${message}`);
}

function run(command, args, options = {}) {
  const result = spawnSync(command, args, { stdio: "inherit", shell: isWindows, ...options });
  if (result.error) throw result.error;
  return result;
}

function supabase(args, options) {
  return run("npx", ["supabase", ...args, "--workdir", STACK_DIR], options);
}

function must(result, what) {
  if (result.status !== 0) {
    console.error(`\n[e2e] ${what} failed (exit ${result.status}).`);
    process.exit(result.status || 1);
  }
  return result;
}

// ---------------------------------------------------------------------------
// 1. The stack's config, derived from the dev one so auth and API settings
//    can never drift apart.
// ---------------------------------------------------------------------------

function writeStackConfig() {
  let section = "";
  const lines = readFileSync("supabase/config.toml", "utf8")
    .split(/\r?\n/)
    .map((line) => {
      const header = line.match(/^\s*\[([^\]]+)\]/);
      if (header) section = header[1];
      if (/^project_id\s*=/.test(line)) return `project_id = "${projectId}"`;
      const port = line.match(/^(\s*(?:port|shadow_port|inspector_port)\s*=\s*)(\d+)(.*)$/);
      if (port) return `${port[1]}${Number(port[2]) + PORT_OFFSET}${port[3]}`;
      if (OFF_SECTIONS.has(section) && /^\s*enabled\s*=\s*true/.test(line)) return line.replace("true", "false");
      return line.replace(/localhost:3000/g, `localhost:${TEST_SERVER_PORT}`);
    });

  mkdirSync(join(STACK_DIR, "supabase"), { recursive: true });
  writeFileSync(
    join(STACK_DIR, "supabase", "config.toml"),
    `# Generated by scripts/e2e.mjs from supabase/config.toml on every run. Do not edit.\n${lines.join("\n")}`,
  );
  rmSync(join(STACK_DIR, "supabase", "migrations"), { recursive: true, force: true });
  cpSync("supabase/migrations", join(STACK_DIR, "supabase", "migrations"), { recursive: true });
}

// ---------------------------------------------------------------------------
// 2-3. Start, reset, seed; record the URL and keys.
// ---------------------------------------------------------------------------

function stackEnv() {
  const status = supabase(["status", "-o", "env"], { stdio: ["ignore", "pipe", "inherit"], encoding: "utf8" });
  must(status, "supabase status");
  const env = parseEnv(status.stdout);
  const url = env.API_URL;
  const anon = env.PUBLISHABLE_KEY ?? env.ANON_KEY;
  const service = env.SECRET_KEY ?? env.SERVICE_ROLE_KEY;
  const mailpit = env.MAILPIT_URL ?? env.INBUCKET_URL;
  if (!url || !anon || !service || !mailpit) {
    console.error("[e2e] `supabase status` did not report the stack's URL, keys and Mailpit URL.");
    process.exit(1);
  }
  return {
    NEXT_PUBLIC_SUPABASE_URL: url,
    NEXT_PUBLIC_SUPABASE_ANON_KEY: anon,
    SUPABASE_SERVICE_ROLE_KEY: service,
    MAILPIT_URL: mailpit,
  };
}

function prepareStack() {
  writeStackConfig();

  if (containerRunning(stackContainer)) {
    step(`e2e stack (${projectId}) is running.`);
  } else {
    step(`Starting the e2e stack (${projectId}, ports 553xx). A minute or two the first time.`);
    must(supabase(["start", "-x", EXCLUDED_SERVICES.join(",")]), "supabase start (e2e stack)");
  }

  step("Resetting the e2e database (all migrations from scratch).");
  must(supabase(["db", "reset"]), "supabase db reset (e2e stack)");

  const env = stackEnv();
  writeFileSync(ENV_FILE, `${Object.entries(env).map(([key, value]) => `${key}=${value}`).join("\n")}\n`);

  step("Seeding the e2e database with e2e-only accounts.");
  must(
    run(process.execPath, ["node_modules/tsx/dist/cli.mjs", "supabase/seed/seed.ts"], {
      shell: false,
      env: { ...process.env, ...env, SEED_ACCOUNTS: "e2e" },
    }),
    "seed (e2e stack)",
  );
  return env;
}

// ---------------------------------------------------------------------------
// 4. The dev database, before and after.
// ---------------------------------------------------------------------------

const DEV_TEST_DATA_SQL = `
  select json_build_object(
    'test_accounts', (select count(*) from auth.users where email ~* '^e2e-.*@drincup\\.test$'),
    'test_orders', (select count(*) from public.orders where idempotency_key like 'e2e-%'
                     or user_id in (select id from auth.users where email ~* '^e2e-.*@drincup\\.test$')));`;

function devSnapshot() {
  if (!containerRunning(devContainer)) return null;
  return { fingerprint: fingerprint(devContainer), testData: psqlJson(devContainer, DEV_TEST_DATA_SQL) };
}

function portInUse(port) {
  return new Promise((resolve) => {
    const socket = connect({ port, host: "localhost" });
    socket.once("connect", () => {
      socket.destroy();
      resolve(true);
    });
    socket.once("error", () => resolve(false));
  });
}

// ---------------------------------------------------------------------------

if (await portInUse(TEST_SERVER_PORT)) {
  console.error(
    `[e2e] Port ${TEST_SERVER_PORT} is already in use. The suite builds and starts its own server there,\n` +
      "      and will not reuse one that may point at another database. Stop it first (README, \"Tests\").",
  );
  process.exit(1);
}

const stack = prepareStack();
const before = devSnapshot();
const runId = `e2e-${new Date().toISOString().replace(/[-:]/g, "").slice(0, 15)}-${randomBytes(2).toString("hex")}`;

step(`Running Playwright against ${stack.NEXT_PUBLIC_SUPABASE_URL} (Stripe metadata e2e_run=${runId}).`);
const playwright = run(process.execPath, ["node_modules/@playwright/test/cli.js", "test", ...process.argv.slice(2)], {
  shell: false,
  env: { ...process.env, ...stack, E2E_RUN_ID: runId },
});

step("Checking the dev database was left exactly as it was.");
let isolationFailed = false;
if (!before) {
  console.log(`      The dev stack (${devContainer}) is not running, so there was nothing to protect; check skipped.`);
} else {
  const after = devSnapshot();
  const changed = fingerprintChanges(before.fingerprint, after.fingerprint);
  console.log(`      orders before: ${before.fingerprint.orders}   orders after: ${after.fingerprint.orders}`);
  console.log(`      test accounts / test orders in the dev database: ${after.testData.test_accounts} / ${after.testData.test_orders}`);
  if (changed.length || after.testData.test_accounts || after.testData.test_orders) {
    isolationFailed = true;
    console.error("[e2e] FAILED: the dev database changed during the run:");
    for (const key of changed) console.error(`      ${key}: ${before.fingerprint[key]} -> ${after.fingerprint[key]}`);
    console.error(
      "      If you used the dev app during the run, that explains it. Otherwise a test reached the dev\n" +
        "      database; `npm run db:clean-test-data` removes test data.",
    );
  } else {
    console.log("      Unchanged.");
  }
}

process.exit(playwright.status || (isolationFailed ? 1 : 0));
